"""add parent_message_id to messages

Revision ID: 22920329f6b6
Revises: 5fb242aa5433
Create Date: 2026-02-15 12:57:53.722272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22920329f6b6'
down_revision: Union[str, Sequence[str], None] = '5fb242aa5433'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('parent_message_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'parent_message_id')
    # ### end Alembic commands ###
